README.md

Preview can be accessed clicking on the "Details" link:

Add support for associating preview of the site with pull requests

---

_data/footer-site-map.yml
index.markdown

This commit workaround limitation of the current nginx server configuration
serving "slicer.org" pages.
See https://github.com/Slicer/slicer.org/pull/79#issuecomment-809697846
Reported-by: James Butler <jbutler@sonovol.com>

BUG: Fix link to Commercial-use internal page explicitly appending ".html"

---

_plugins/feed_generator_override.rb

This commit is a follow up of 561c6eb01  (Disable unused "jekyll-feed" plugin)
to ensure feed generation is disabled.
Since jekyll-feed is a dependency of bulma-clean-theme, it is implicitly
enabled.
Without a setting to disable the feed generation, this commit applies the workaround
documented in https://github.com/jekyll/minima/issues/562#issuecomment-735120020
See #50

Force disabling for feed generation

---

_config_download.yml
download.markdown

This commit removes the extra space causing the following error when
using the generated download templates:
```
File "/home/jcfr/Projects/slicer_download/slicer_download_server/templates/download.html", line 283, in template
<a href="{{%20download_stats_url%20}}" class="navbar-item">
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
```

download: Fix jinja2 template associated with download_stats_url

---

_includes/header.html

This ensures that the link from the generated download site is associated
with the url specified in _config.yml (aka `url: "https://slicer.org"`)

_includes/header: Fix "3D Slicer" link associated with download site

---

.github/workflows/build-website.yml
README.md

See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

ci: Fix deployment using ubuntu-20.04 instead of obsolete ubuntu-16.04

---

index.markdown

Use the same link as already used in the footer instead of the old link to the Slicer wiki.

Update "Citing Slicer" link to point to readthedocs

---

.github/workflows/build-website.yml
README.md

Since secret are not available in fork, this commit skips the job if
token is not available.
See https://github.community/t/make-secrets-available-to-builds-of-forks/16166

ci: Skip deployment of "deploy-download-preview" if token not available

---

.github/dependabot.yml
.github/workflows/build-website.yml

* Pin GitHub actions to full length commit SHA.
* GitHub's security hardening guide recommends this mitigation method.
* See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
* Add Dependabot workflow to update GitHub Actions:
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
* https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#enabling-dependabot-version-updates-for-actions
Adapted from work done by @jamesobutler in:
* https://github.com/Slicer/Slicer/pull/6888

Add Dependabot workflow to update GitHub Actions

---

.github/workflows/build-website.yml

Related to:
* https://github.com/Slicer/slicer.org/pull/174

ci: Fix build-website GitHub Actions workflow updating Ruby from 2.6 to 2.7

---

netlify.toml

This pull request is intended to fix:
* https://github.com/Slicer/slicer.org/pull/174
References:
* https://docs.netlify.com/configure-builds/file-based-configuration/#build-settings
* https://docs.netlify.com/configure-builds/available-software-at-build-time/#languages

ci: Ensure netlify worker also uses Ruby 2.7

---

.github/workflows/build-website.yml
_data/template_test_data/download_incomplete_releases.json
_includes/download_table_td.html

This fixes error like the following reported when including parameter like the following in the URL: `?os=<operating_system>` where `<operating_system>` is any of `(linux, win, macosx)`
Error:
```
Traceback (most recent call last):
File "/app/entrypoint.py", line 12, in <module>
context.render_template()
File "/app/main.py", line 40, in render_template
file.write(template.render(**self._variables) + '\n')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "/usr/local/lib/python3.11/site-packages/jinja2/_compat.py", line 28, in …
```

download: Add support for incomplete releases

---

.github/actions/screenshot-website-imgur-upload/action.yml
_layouts/default.html
_sass/classes.sass
assets/js/app.js
download.markdown

* site: Ensure up-to-date version of "app.js" is always fetched
* download: Ensure clicking on a tab scrolls just above the tabs area
* download: Update "Checksums" tab to wrap detailed instruction
* download: Change default tab from "Checksums" to "Package Naming Convention"

Download: Change default tab to "Package Naming Convention" / Fix scrolling on tab click / Impove layout of "Checksums" tab

---

commercial-use.markdown

This updates the section about SonoVol to change to past-tense and provide information about which company now owns the technology. 
The SonoVol logo can remain to reflect the original Kitware blog. 
- SonoVol->PerkinElmer was described in this Kitware [blog post](https://www.kitware.com/kitwares-long-standing-collaboration-with-sonovol-has-enabled-continued-success/)
- Now PerkinElmer LifeSciences -> Revvity, Inc.
#WeAreRevvity
https://www.revvity.com/

commercial-use: Update current state about SonoVol

---

.github/workflows/build-website.yml
README.md
_config_download_maintenance.yml
_config_netlify_deploy_download_maintenance_preview.yml
download.markdown
netlify.toml

This branch is expected to be manually checkout on the server while the maintenance is taking place.

Add support for publishing download site maintenance branch

---

_config_download_maintenance.yml

See https://discourse.slicer.org/t/maintenance-of-download-slicer-org-slicer-kitware-com-and-slicer-packages-kitware-com-planned-for-march-28th-2024-3-30pm-to-5-00pm-et/35155

download: Update maintenance page settings

---

_data/footer-site-map.yml
commercial-use.markdown
index.markdown

The 3DSlicerApp account on X.com (formerly Twitter) has not been active since March 2023. LinkedIn continues to be a focused place for researchers to post about their work in an academic/professional setting unlike X.com that covers a wide spectrum of topics. Therefore LinkedIn may be considered more appropriate for connecting researchers to others in more helpful ways.
Previously discussed in https://discourse.slicer.org/t/social-media-presence-moving-away-from-twitter/30433/8.

Switch highlighted social network to LinkedIn

---

.github/workflows/build-website.yml

As of 2025-01-08, the latest version of `cuchi/jinja2-action` broke due to a breaking change introduced in poetry 2.0:
* https://github.com/cuchi/jinja2-action/pull/21
* https://github.com/cuchi/jinja2-action/issues/22
This fork was created to provide the fix originally contributed by @OlivierCloudar, ensuring it is associated with a GitHub organization rather than an individual user account.
See https://github.com/Slicer/jinja2-action

fix: Use Slicer fork of jinja2-action to fix Poetry 2.0 breaking change

---

Gemfile
Gemfile.lock
_config.yml
_config_download.yml
_includes/header.html
_includes/navbar-column.html
_includes/sitemap-column.html

This pull request addresses issues where navigating between internal pages and those hosted on an auxiliary site would open additional tabs. The following key changes have been introduced:
1. **Setting the top-level `url` configuration** to match the auxiliary site’s actual URL. This ensures:
- Links to the download site are treated as internal, preventing unnecessary new tab openings.
- Various `<meta>` elements, as well as generated files such as `browserconfig.xml`, `robots.txt`, and `sitemap.xml`, correctly reference `https://download.slicer.org` instead of `https://slicer.org`.
2. **Introducing the `is_primary_site` config variable** to differentiate between the primary site (`slicer.org`) and auxiliary sites (e.g., `download.slicer.org`). This variable is now used in the `header`, …

Ensure seamless navigation between primary (`slicer.org`) and auxiliary sites (`download.slicer.org`)

---

_data/footer-site-map.yml
_includes/hero-main.html
_includes/navbar-column.html
_includes/sitemap-column.html
index.markdown

Ensure seamless navigation from primary (`slicer.org`) to auxiliary (`download.slicer.org`) site.
Set `link_class` to handle links with the `force-internal-link` class, preventing auxiliary site links from opening in a new tab.
Modify `footer-site-map.yml` and hero buttons to support `link_class`.

fix: Always handle download link as internal

---

.github/dependabot.yml

This is expected to address the following error introduced in 5abe070 ("fix: Use Slicer fork of jinja2-action to fix Poetry 2.0 breaking change", 2025-01-08)
> Dependabot could not find a dependency version.
> Dependabot could not resolve semantic versions for dependencies : Slicer/jinja2-action

ci: Attempt to fix dependabot failure to resolve "Slicer/jinja2-action" version

---

.github/workflows/build-website.yml

This is expected to address the following error introduced in 5abe070 ("fix: Use Slicer fork of jinja2-action to fix Poetry 2.0 breaking change", 2025-01-08)
> Dependabot could not find a dependency version.
> Dependabot could not resolve semantic versions for dependencies : Slicer/jinja2-action
Instead of either listing "Slicer/jinja2-action" as dependency to ignore in `dependatbot.yml` (https://github.com/Slicer/slicer.org/pull/298) or adding comment including multiple strings (https://github.com/Slicer/slicer.org/pull/299), this commit switches to a version tagged and released explicitly within the "Slicer/jinja2-action" project.

ci: Last attempt to fix dependabot failure to resolve "Slicer/jinja2-action" version

---

_sass/classes.sass

| Before | After |
|--|--|
| ![image](https://github.com/user-attachments/assets/1ce16723-d60e-4599-99ba-29ee56a05b16) | ![image](https://github.com/user-attachments/assets/39e9c176-5153-4f06-a600-af1e3c8a4b68) |

fix: Allow page subtitle to standout adding top margin

---

_config.yml
_includes/footer.html

Introduce two new site variables for improved flexibility in rendering the revision link:
- `github_repository`: Specifies the GitHub repository hosting the site sources (always set).
- `github_short_sha`: Optionally set to a predefined value; if not initialized, it defaults to the value retrieved using the `project_version` Jekyll plugin.
This ensures that the revision link in the footer correctly references the intended repository and commit, even when `github_short_sha` is externally provided.

fix: Allow customization of revision link in footer

---

_config.yml
_config_dev.yml
_data/footer-site-map.yml
index.markdown

Update from https://www.slicer.org/wiki/Documentation/Nightly/Training to https://training.slicer.org

feat: Use updated URL for training site

---

.github/workflows/build-website.yml

Ubuntu 20 image is retired as of April 15th, 2025. https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
This is a follow-up to https://github.com/Slicer/slicer.org/commit/6a7e239f5602d4f0f0df0eda0510bd0766cbcc0d when the Ubuntu image was bumped from 16.04 to 20.04.

ci: Fix deployment using ubuntu-24.04 instead of obsolete ubuntu-20.04

---

_data/template_test_data/download_incomplete_releases.json
_data/template_test_data/download_only_nightly.json
_data/template_test_data/download_only_release.json
_data/template_test_data/download_release_and_nightly.json
_includes/download_table_td.html
_sass/classes.sass

Related `slicer_download` update: https://github.com/Slicer/slicer_download/commit/2a29258e9199cb3a8a1f07f020c1a39559f4f55d (`slicer_download_server: Set "extensions_browse_url" metadata`)
---
|Before | After |
|--|--|
| ![image](https://github.com/user-attachments/assets/b512eb3c-52a8-4606-84c9-9c6a2803fa53) |  ![image](https://github.com/user-attachments/assets/3e214443-22e6-4d18-9b77-18135d7808f6) |

download: Add "browse extensions" link for each Slicer version
